name: Add Fix Version to Jira Issue
on:
  push:
    branches:
    - 'dev'
jobs:
  addfixversiontojiraissue:
    name: 'Add Fix Version to Jira Issue'
    runs-on: ubuntu-latest
  
    steps:
        - id: getrelease
          uses: pozetroninc/github-action-get-latest-release@master
          with:
            repository: ${{ github.repository }}
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Checkout dev branch
          run: git checkout dev
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - run: npm install --no-package-lock --no-save @actions/github request
        - name: Run fix version script
          run: LATEST_RELEASE=${{ steps.getrelease.outputs.release }} AUTH=${{ secrets.JIRA_AUTH}} PROJECT_ID=${{ secrets.JIRA_PROJECT_ID}} node ./.github/actions/addFixVersionToJiraIssue.js