name: Add Fix Version to Jira Issue
on:
  push:
    branches:
    - 'dev'
jobs:
  addfixversiontojiraissue:
    name: 'Add Fix Version to Jira Issue'
    runs-on: ubuntu-latest
  
    steps:
        - id: keydb
          uses: pozetroninc/github-action-get-latest-release@master
          with:
            repository: ${{ github.repository }}
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Checkout dev branch
          run: git checkout dev
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - run: npm install --no-package-lock --no-save @actions/core @actions/github
        - name: Run fix version script
          run: node ./.github/actions/addFixVersionToJiraIssue.js
          with:
            latestRelease: ${{ steps.keydb.outputs.release }}